use std::error::Error;

use rutilus_domain::AuditFailure;
use rutilus_migration::Migrator;
use sea_orm::{
    ActiveModelTrait, ColumnTrait, ConnectOptions, ConnectionTrait, Database, DatabaseConnection,
    EntityTrait, QueryFilter, Set,
};
use sea_orm_migration::MigratorTrait;
use time::OffsetDateTime;
use uuid::Uuid;

const AUDIT_FAILURE_VOCABULARY_MIGRATION: &str = "m20260813_000003_audit_failure_vocabulary";

/// The exhaustive domain-side enumeration of [`AuditFailure`]: the `match`
/// has no wildcard arm, so adding a variant to the domain enum fails this
/// file's compilation instead of silently leaving the schema-binding
/// expectations stale — the exhaustive-pin style the domain vocabulary
/// itself uses.
fn pin_audit_failure_vocabulary(failure: AuditFailure) {
    use AuditFailure::{
        AuthenticationFailed, CapabilityUnsupported, CenterRequestRefused, CenterStoreFailed,
        CoreResourceReadFailed, CredentialUnavailable, CsvInvalid, EndpointImportRowFailed,
        EndpointPersistenceFailed, RedfishDiscoveryFailed, SessionRevocationFailed,
        SnapshotPersistenceFailed, TlsTrustFailed,
    };
    match failure {
        CredentialUnavailable
        | TlsTrustFailed
        | RedfishDiscoveryFailed
        | EndpointPersistenceFailed
        | CoreResourceReadFailed
        | SnapshotPersistenceFailed
        | CsvInvalid
        | EndpointImportRowFailed
        | CenterStoreFailed
        | CenterRequestRefused
        | AuthenticationFailed
        | SessionRevocationFailed
        | CapabilityUnsupported => {}
    }
}

/// Every [`AuditFailure`] variant, in enum order — the iteration list of
/// the schema-binding test. [`pin_audit_failure_vocabulary`] makes the list
/// compile-exhaustive: a variant added to the enum fails the pin's `match`
/// whether or not this list is updated, so the two sides of the binding can
/// never drift silently.
const ALL_FAILURES: [AuditFailure; 13] = [
    AuditFailure::CredentialUnavailable,
    AuditFailure::TlsTrustFailed,
    AuditFailure::RedfishDiscoveryFailed,
    AuditFailure::EndpointPersistenceFailed,
    AuditFailure::CoreResourceReadFailed,
    AuditFailure::SnapshotPersistenceFailed,
    AuditFailure::CsvInvalid,
    AuditFailure::EndpointImportRowFailed,
    AuditFailure::CenterStoreFailed,
    AuditFailure::CenterRequestRefused,
    AuditFailure::AuthenticationFailed,
    AuditFailure::SessionRevocationFailed,
    AuditFailure::CapabilityUnsupported,
];

// The test walks the full failure vocabulary and the target-principal
// column, so it exceeds the pedantic line budget (same exception as the
// rebuild migrations' copy steps).
#[allow(clippy::too_many_lines)]
#[tokio::test]
async fn full_failure_vocabulary_and_target_principal_persist_foreign_shapes_are_refused()
-> Result<(), Box<dyn Error>> {
    let (_directory, database) = connect().await?;
    Migrator::up(&database, None).await?;
    let occurred_at = OffsetDateTime::now_utc();

    // Direction 1 (domain → schema), generated by the domain itself: every
    // `AuditFailure` variant's stable code persists through the real schema
    // on a failed terminal event and reads back — a code added to the enum
    // must land in the CHECK before this test passes, and the expected set
    // comes from the enum, never from a transcribed list that could drift
    // with it.
    let mut expected_codes: Vec<&str> = Vec::new();
    for variant in ALL_FAILURES {
        pin_audit_failure_vocabulary(variant);
        let expected = variant.as_str();
        expected_codes.push(expected);
        let inserted = insert_failed_execute_row(&database, expected, occurred_at).await?;
        let stored = rutilus_entity::audit_event::Entity::find_by_id(inserted.id)
            .one(&database)
            .await?
            .ok_or("inserted audit row is missing")?;
        assert_eq!(stored.failure.as_deref(), Some(expected));
        assert_eq!(stored.verification.as_deref(), Some("rejected"));
    }

    // Direction 2 (schema → domain): the `failure IN (...)` list of the
    // live CHECK, read from the schema's own DDL, must be exactly the
    // domain vocabulary — the CHECK cannot carry a code the domain does not
    // know without the test refusing it.
    let mut expected_sorted = expected_codes.clone();
    expected_sorted.sort_unstable();
    let mut schema_sorted = live_failure_check_codes(&database).await?;
    schema_sorted.sort_unstable();
    assert_eq!(
        expected_sorted, schema_sorted,
        "the live CHECK must accept exactly the domain failure vocabulary"
    );

    // A failure code the vocabulary does not know at all is refused.
    let unknown = insert_failed_execute_row(&database, "binding-code-expired", occurred_at).await;
    assert!(unknown.is_err(), "an unknown failure code must be refused");

    // The S3-4 target principal persists on a change-password row: the
    // administrator-issued password set records the user whose credential
    // was replaced under the action that names a distinct subject.
    let target_principal_id = Uuid::now_v7();
    let changed =
        insert_change_password_row(&database, Some(target_principal_id), occurred_at).await?;
    let stored = rutilus_entity::audit_event::Entity::find_by_id(changed.id)
        .one(&database)
        .await?
        .ok_or("inserted audit row is missing")?;
    assert_eq!(stored.target_principal_id, Some(target_principal_id));
    assert_eq!(stored.action, "change-password");
    assert!(stored.actor_principal_id.is_some());

    // A target principal under an action that names no subject distinct
    // from its actor is refused: the `ck_audit_events_target_principal`
    // CHECK pins the same shape rule the domain contract states.
    let misplaced = insert_login_with_target_row(&database, occurred_at).await;
    assert!(
        misplaced.is_err(),
        "a target principal under login must be refused"
    );

    Ok(())
}

#[tokio::test]
async fn rebuild_preserves_existing_audit_rows() -> Result<(), Box<dyn Error>> {
    let (_directory, database) = connect().await?;

    // Apply every migration before the vocabulary rebuild: the audit table
    // still has the 000001 shapes, which the legacy rows prove — one
    // execution row and one failed center row under an 000001 failure code.
    // The step count is the migration's own registration position, so the
    // test stays correct however later slices extend the registration list.
    let steps = migrations_before(AUDIT_FAILURE_VOCABULARY_MIGRATION)?;
    Migrator::up(&database, Some(steps)).await?;
    let execution_id = Uuid::now_v7();
    insert_raw_audit_row(
        &database,
        execution_id,
        "execute-operation",
        "execute-operations",
        "endpoint",
        Some(Uuid::now_v7()),
        "reset-system",
        None,
        "succeeded",
    )
    .await?;
    let center_failure_id = Uuid::now_v7();
    insert_raw_audit_row(
        &database,
        center_failure_id,
        "register-site-binding",
        "manage-center-bindings",
        "product",
        None,
        "none",
        Some("center-request-refused"),
        "failed",
    )
    .await?;

    // The rebuild preserves every legacy row, with the new target column
    // reading NULL.
    Migrator::up(&database, None).await?;
    let stored = rutilus_entity::audit_event::Entity::find_by_id(execution_id)
        .one(&database)
        .await?
        .ok_or("the legacy execution row must survive the rebuild")?;
    assert_eq!(stored.action, "execute-operation");
    assert_eq!(stored.redfish_operation, "reset-system");
    assert_eq!(stored.target_principal_id, None);
    let stored = rutilus_entity::audit_event::Entity::find_by_id(center_failure_id)
        .one(&database)
        .await?
        .ok_or("the legacy center row must survive the rebuild")?;
    assert_eq!(stored.action, "register-site-binding");
    assert_eq!(stored.failure.as_deref(), Some("center-request-refused"));
    assert_eq!(stored.target_principal_id, None);

    Ok(())
}

#[tokio::test]
async fn down_refuses_unrepresentable_rows_and_restores_the_000001_shapes()
-> Result<(), Box<dyn Error>> {
    let (_directory, database) = connect().await?;
    Migrator::up(&database, None).await?;
    let occurred_at = OffsetDateTime::now_utc();

    // Rows written in the widened shapes: the two new failure codes and one
    // change-password row carrying a target principal.
    let session_revocation =
        insert_failed_execute_row(&database, "session-revocation-failed", occurred_at).await?;
    let capability =
        insert_failed_execute_row(&database, "capability-unsupported", occurred_at).await?;
    insert_change_password_row(&database, Some(Uuid::now_v7()), occurred_at).await?;
    assert!(
        rutilus_entity::audit_event::Entity::find_by_id(session_revocation.id)
            .one(&database)
            .await?
            .is_some()
    );
    assert!(
        rutilus_entity::audit_event::Entity::find_by_id(capability.id)
            .one(&database)
            .await?
            .is_some()
    );

    // Two rollbacks reach the 000003 down: the 000004 rollback in front
    // succeeds — the rows are representable in the 000003 shape, which keeps
    // the target column and the thirteen failure codes — and the 000003 down
    // then refuses the target-principal row: the restored 000001 shape has
    // no column for it, and silently dropping the target would falsify the
    // audit record rather than refuse it.
    let refused_target = Migrator::down(&database, Some(2)).await;
    assert!(
        refused_target.is_err(),
        "the down must refuse rows carrying a target principal"
    );
    rutilus_entity::audit_event::Entity::delete_many()
        .filter(rutilus_entity::audit_event::Column::TargetPrincipalId.is_not_null())
        .exec(&database)
        .await?;

    // Without the target row, the two new failure codes still refuse the
    // down: the restored eleven-code CHECK rejects them during the copy,
    // exactly like the 000001 down refuses its center rows.
    let refused_codes = Migrator::down(&database, Some(2)).await;
    assert!(
        refused_codes.is_err(),
        "the down must refuse rows carrying the new failure codes"
    );
    rutilus_entity::audit_event::Entity::delete_many()
        .exec(&database)
        .await?;
    Migrator::down(&database, Some(2)).await?;

    // The restored 000001 shape refuses the two new codes again while the
    // eleven codes it already knew stay accepted. The rows go through raw
    // SQL because the entity model names the `target_principal_id` column
    // the restored table no longer has (the product-users rollback's
    // precedent).
    for code in ["session-revocation-failed", "capability-unsupported"] {
        let refused = insert_raw_audit_row(
            &database,
            Uuid::now_v7(),
            "execute-operation",
            "execute-operations",
            "endpoint",
            Some(Uuid::now_v7()),
            "reset-system",
            Some(code),
            "failed",
        )
        .await;
        assert!(
            refused.is_err(),
            "the rolled-back schema must not know {code}"
        );
    }
    insert_raw_audit_row(
        &database,
        Uuid::now_v7(),
        "execute-operation",
        "execute-operations",
        "endpoint",
        Some(Uuid::now_v7()),
        "reset-system",
        Some("authentication-failed"),
        "failed",
    )
    .await?;
    // The restored table has no target column at all: an insert that names
    // it is refused by the schema itself.
    let no_column = database
        .execute_unprepared(&format!(
            "INSERT INTO audit_events \
             (id, operation_id, event_sequence, actor, actor_principal_id, \
              target_principal_id, origin, target_kind, target_endpoint_id, \
              target_endpoint_address, parameter_kind, credential_id, trust_mode, \
              row_count, permission, action, redfish_operation, outcome, progress, \
              failure, verification, occurred_at) \
             VALUES ('{id}', '{operation_id}', 2, 'user', '{principal}', \
              '{target}', 'standalone', 'product', NULL, NULL, 'endpoint-refresh', \
              NULL, NULL, NULL, 'authenticate', 'change-password', 'none', \
              'succeeded', NULL, NULL, 'confirmed', '2026-08-07 12:00:00')",
            id = Uuid::now_v7(),
            operation_id = Uuid::now_v7(),
            principal = Uuid::now_v7(),
            target = Uuid::now_v7(),
        ))
        .await;
    assert!(
        no_column.is_err(),
        "the rolled-back schema must have no target_principal_id column"
    );

    Ok(())
}

/// The codes of one `IN (...)` list inside a `CREATE TABLE` DDL, anchored on
/// the constrained column — the schema side of the domain↔CHECK binding,
/// read from the real DDL instead of a transcribed list, so the test
/// compares the actual CHECK against the actual domain vocabulary.
fn in_list_codes(ddl: &str, anchor: &str) -> Result<Vec<String>, Box<dyn Error>> {
    let marker = format!("{anchor} IN (");
    let start = ddl
        .find(&marker)
        .ok_or_else(|| format!("no `{marker}` list in the DDL"))?
        + marker.len();
    // The list's literals nest no parentheses, so the first `)` closes it.
    let end = ddl[start..]
        .find(')')
        .ok_or_else(|| format!("the `{anchor} IN (` list is not closed"))?
        + start;
    Ok(ddl[start..end]
        .split(',')
        .map(|code| code.trim().trim_matches('\'').to_owned())
        .collect())
}

/// The `failure IN (...)` codes of the live `audit_events` CHECK.
async fn live_failure_check_codes(
    database: &DatabaseConnection,
) -> Result<Vec<String>, Box<dyn Error>> {
    use sea_orm::sea_query::{Alias, Expr, Query};
    let statement = Query::select()
        .expr(Expr::cust("sql"))
        .from(Alias::new("sqlite_master"))
        .cond_where(Expr::cust("type = 'table' AND name = 'audit_events'"))
        .to_owned();
    let row = database
        .query_one(&statement)
        .await?
        .ok_or("audit_events is not in the live schema")?;
    let ddl: String = row.try_get_by_index(0)?;
    in_list_codes(&ddl, "failure")
}

/// The number of registered migrations before the named migration.
fn migrations_before(name: &str) -> Result<u32, Box<dyn Error>> {
    let migrations = Migrator::migrations();
    let position = migrations
        .iter()
        .position(|migration| migration.name() == name)
        .ok_or("audit failure vocabulary migration is not registered")?;
    Ok(u32::try_from(position)?)
}

/// Writes one failed terminal audit row in the §16.3 execution shape with
/// the given failure code.
async fn insert_failed_execute_row(
    database: &DatabaseConnection,
    failure: &str,
    occurred_at: OffsetDateTime,
) -> Result<rutilus_entity::audit_event::Model, sea_orm::DbErr> {
    rutilus_entity::audit_event::ActiveModel {
        id: Set(Uuid::now_v7()),
        operation_id: Set(Uuid::now_v7()),
        event_sequence: Set(2),
        actor: Set(String::from("system")),
        actor_principal_id: Set(None),
        target_principal_id: Set(None),
        origin: Set(String::from("standalone")),
        target_kind: Set(String::from("endpoint")),
        target_endpoint_id: Set(Some(Uuid::now_v7())),
        target_endpoint_address: Set(None),
        parameter_kind: Set(String::from("endpoint-refresh")),
        credential_id: Set(None),
        trust_mode: Set(None),
        row_count: Set(None),
        permission: Set(String::from("execute-operations")),
        action: Set(String::from("execute-operation")),
        redfish_operation: Set(String::from("reset-system")),
        outcome: Set(String::from("failed")),
        progress: Set(None),
        failure: Set(Some(failure.to_owned())),
        verification: Set(Some(String::from("rejected"))),
        occurred_at: Set(occurred_at),
    }
    .insert(database)
    .await
}

/// Writes one succeeded `change-password` row in the §16.2 authentication
/// shape, optionally naming the principal whose credential was replaced
/// (S3-4).
async fn insert_change_password_row(
    database: &DatabaseConnection,
    target_principal_id: Option<Uuid>,
    occurred_at: OffsetDateTime,
) -> Result<rutilus_entity::audit_event::Model, sea_orm::DbErr> {
    rutilus_entity::audit_event::ActiveModel {
        id: Set(Uuid::now_v7()),
        operation_id: Set(Uuid::now_v7()),
        event_sequence: Set(2),
        actor: Set(String::from("user")),
        actor_principal_id: Set(Some(Uuid::now_v7())),
        target_principal_id: Set(target_principal_id),
        origin: Set(String::from("standalone")),
        target_kind: Set(String::from("product")),
        target_endpoint_id: Set(None),
        target_endpoint_address: Set(None),
        parameter_kind: Set(String::from("endpoint-refresh")),
        credential_id: Set(None),
        trust_mode: Set(None),
        row_count: Set(None),
        permission: Set(String::from("authenticate")),
        action: Set(String::from("change-password")),
        redfish_operation: Set(String::from("none")),
        outcome: Set(String::from("succeeded")),
        progress: Set(None),
        failure: Set(None),
        verification: Set(Some(String::from("confirmed"))),
        occurred_at: Set(occurred_at),
    }
    .insert(database)
    .await
}

/// Writes one succeeded `login` row carrying a target principal — the shape
/// the `ck_audit_events_target_principal` CHECK must refuse.
async fn insert_login_with_target_row(
    database: &DatabaseConnection,
    occurred_at: OffsetDateTime,
) -> Result<rutilus_entity::audit_event::Model, sea_orm::DbErr> {
    rutilus_entity::audit_event::ActiveModel {
        id: Set(Uuid::now_v7()),
        operation_id: Set(Uuid::now_v7()),
        event_sequence: Set(2),
        actor: Set(String::from("user")),
        actor_principal_id: Set(Some(Uuid::now_v7())),
        target_principal_id: Set(Some(Uuid::now_v7())),
        origin: Set(String::from("standalone")),
        target_kind: Set(String::from("product")),
        target_endpoint_id: Set(None),
        target_endpoint_address: Set(None),
        parameter_kind: Set(String::from("endpoint-refresh")),
        credential_id: Set(None),
        trust_mode: Set(None),
        row_count: Set(None),
        permission: Set(String::from("authenticate")),
        action: Set(String::from("login")),
        redfish_operation: Set(String::from("none")),
        outcome: Set(String::from("succeeded")),
        progress: Set(None),
        failure: Set(None),
        verification: Set(Some(String::from("confirmed"))),
        occurred_at: Set(occurred_at),
    }
    .insert(database)
    .await
}

/// Writes one terminal audit row through raw SQL — the only way to write to
/// an `audit_events` schema without the `target_principal_id` column, which
/// the entity model names (the product-users rollback's precedent).
#[allow(clippy::too_many_arguments)]
async fn insert_raw_audit_row(
    database: &DatabaseConnection,
    id: Uuid,
    action: &str,
    permission: &str,
    target_kind: &str,
    target_endpoint_id: Option<Uuid>,
    redfish_operation: &str,
    failure: Option<&str>,
    outcome: &str,
) -> Result<(), sea_orm::DbErr> {
    let target_endpoint = match target_endpoint_id {
        Some(target_endpoint_id) => format!("X'{}'", target_endpoint_id.simple()),
        None => String::from("NULL"),
    };
    let failure = match failure {
        Some(code) => format!("'{code}'"),
        None => String::from("NULL"),
    };
    let verification = if outcome == "succeeded" {
        "'confirmed'"
    } else {
        "'rejected'"
    };
    database
        .execute_unprepared(&format!(
            "INSERT INTO audit_events \
             (id, operation_id, event_sequence, actor, actor_principal_id, origin, \
              target_kind, target_endpoint_id, target_endpoint_address, parameter_kind, \
              credential_id, trust_mode, row_count, permission, action, redfish_operation, \
              outcome, progress, failure, verification, occurred_at) \
             VALUES (X'{id}', X'{operation_id}', 2, 'system', NULL, 'standalone', \
              '{target_kind}', {target_endpoint}, NULL, 'endpoint-refresh', NULL, NULL, \
              NULL, '{permission}', '{action}', '{redfish_operation}', '{outcome}', NULL, \
              {failure}, {verification}, '2026-08-07 12:00:00')",
            id = id.simple(),
            operation_id = Uuid::now_v7().simple(),
        ))
        .await
        .map(|_| ())
}

/// Opens one database in a fresh temporary directory.
///
/// The `TempDir` is returned with the connection so it outlives `connect`:
/// dropping it here would unlink the database file while the pool's eager
/// connection still holds it open — harmless on Windows (an open file cannot
/// be deleted), but on Linux the unlink succeeds and the first write
/// statement then fails while creating the rollback journal (the journal
/// open stats the journal path (database path plus "-journal"), which no longer exists, surfacing as
/// `SQLITE_IOERR_FSTAT` / "disk I/O error" on CI).
async fn connect() -> Result<(tempfile::TempDir, DatabaseConnection), Box<dyn Error>> {
    let directory = tempfile::tempdir()?;
    let database_path = directory.path().join("rutilus.db");
    let normalized_path = database_path.to_string_lossy().replace('\\', "/");
    let mut options = ConnectOptions::new(format!("sqlite://{normalized_path}?mode=rwc"));
    options.max_connections(1);
    let database = Database::connect(options).await?;
    Ok((directory, database))
}
