//! Product sessions (§16.2 登录安全).
//!
//! A sign-in creates one [`Session`] row: the client presents a random bearer
//! token, and the row stores only the SHA-256 hash of that token (and of the
//! CSRF token, §16.2 "CSRF 防护"), so the database never holds a usable
//! session secret. Sessions expire by time and are revoked explicitly —
//! §16.2 "密码或角色变化撤销旧 Session" — and revocation is a soft write: the
//! `revoked_at` column is set, the row is never physically deleted, so the
//! session history stays auditable and a revoked token keeps failing its
//! lookup for exactly as long as the row exists.
//!
//! The token values themselves are generated by the security crate; this
//! module only carries their hashes and the session lifecycle.

use std::{error::Error, fmt};

use time::OffsetDateTime;

use crate::{PrincipalId, SessionId};

/// One signed-in product session (§16.2).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Session {
    id: SessionId,
    principal_id: PrincipalId,
    token_hash: [u8; 32],
    csrf_hash: [u8; 32],
    created_at: OffsetDateTime,
    last_used_at: OffsetDateTime,
    expires_at: OffsetDateTime,
    revoked_at: Option<OffsetDateTime>,
}

impl Session {
    /// Opens a new session.
    ///
    /// The caller supplies the clock and the expiry bound. The first use time
    /// equals the creation time until persistence records an activity.
    #[must_use]
    pub fn new(
        id: SessionId,
        principal_id: PrincipalId,
        token_hash: [u8; 32],
        csrf_hash: [u8; 32],
        created_at: OffsetDateTime,
        expires_at: OffsetDateTime,
    ) -> Self {
        Self {
            id,
            principal_id,
            token_hash,
            csrf_hash,
            created_at,
            last_used_at: created_at,
            expires_at,
            revoked_at: None,
        }
    }

    /// Rehydrates a persisted session record.
    ///
    /// The database has no timeline constraint (mirroring the group
    /// precedent), so a stored row with an inconsistent timeline is refused
    /// here as a corrupt aggregate.
    ///
    /// # Errors
    ///
    /// Returns [`SessionRestoreError`] when the expiry does not follow the
    /// creation time, the last use precedes the creation time, or the
    /// revocation time precedes the creation time.
    #[allow(
        clippy::too_many_arguments,
        reason = "the rehydration surface mirrors the persisted row column for column"
    )]
    pub fn try_from_parts(
        id: SessionId,
        principal_id: PrincipalId,
        token_hash: [u8; 32],
        csrf_hash: [u8; 32],
        created_at: OffsetDateTime,
        last_used_at: OffsetDateTime,
        expires_at: OffsetDateTime,
        revoked_at: Option<OffsetDateTime>,
    ) -> Result<Self, SessionRestoreError> {
        if expires_at <= created_at {
            return Err(SessionRestoreError::InvalidTimeline);
        }
        if last_used_at < created_at {
            return Err(SessionRestoreError::InvalidTimeline);
        }
        if revoked_at.is_some_and(|revoked_at| revoked_at < created_at) {
            return Err(SessionRestoreError::InvalidTimeline);
        }
        Ok(Self {
            id,
            principal_id,
            token_hash,
            csrf_hash,
            created_at,
            last_used_at,
            expires_at,
            revoked_at,
        })
    }

    /// Records session activity at the persistence boundary.
    ///
    /// # Errors
    ///
    /// Returns [`SessionRestoreError::InvalidTimeline`] when the activity
    /// time precedes the last recorded use.
    pub fn touch(&mut self, at: OffsetDateTime) -> Result<(), SessionRestoreError> {
        if at < self.last_used_at {
            return Err(SessionRestoreError::InvalidTimeline);
        }
        self.last_used_at = at;
        Ok(())
    }

    /// Revokes this session, refusing to revoke it twice.
    ///
    /// Revocation is the soft write of §16.2: the row stays for audit and the
    /// revoked token keeps failing, but the session is over. A second
    /// revocation is refused because it would move `revoked_at` and rewrite
    /// the historical fact.
    ///
    /// # Errors
    ///
    /// Returns [`SessionError::AlreadyRevoked`] when the session was already
    /// revoked, or [`SessionRestoreError::InvalidTimeline`] when the
    /// revocation time precedes the creation time.
    pub fn revoke(&mut self, at: OffsetDateTime) -> Result<(), SessionError> {
        if self.revoked_at.is_some() {
            return Err(SessionError::AlreadyRevoked);
        }
        if at < self.created_at {
            return Err(SessionRestoreError::InvalidTimeline.into());
        }
        self.revoked_at = Some(at);
        Ok(())
    }

    /// Reports whether this session may serve a request at `at`.
    ///
    /// An active session is one that is not revoked and has not expired.
    #[must_use]
    pub fn is_active(&self, at: OffsetDateTime) -> bool {
        self.revoked_at.is_none() && at < self.expires_at
    }

    #[must_use]
    pub const fn id(&self) -> SessionId {
        self.id
    }

    #[must_use]
    pub const fn principal_id(&self) -> PrincipalId {
        self.principal_id
    }

    #[must_use]
    pub const fn token_hash(&self) -> &[u8; 32] {
        &self.token_hash
    }

    #[must_use]
    pub const fn csrf_hash(&self) -> &[u8; 32] {
        &self.csrf_hash
    }

    #[must_use]
    pub const fn created_at(&self) -> OffsetDateTime {
        self.created_at
    }

    #[must_use]
    pub const fn last_used_at(&self) -> OffsetDateTime {
        self.last_used_at
    }

    #[must_use]
    pub const fn expires_at(&self) -> OffsetDateTime {
        self.expires_at
    }

    #[must_use]
    pub const fn revoked_at(&self) -> Option<OffsetDateTime> {
        self.revoked_at
    }
}

/// A persisted session record violates a domain invariant.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SessionRestoreError {
    /// The stored expiry, last use, or revocation time is inconsistent with
    /// the creation time.
    InvalidTimeline,
}

impl fmt::Display for SessionRestoreError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidTimeline => {
                formatter.write_str("session timeline is inconsistent with its creation time")
            }
        }
    }
}

impl Error for SessionRestoreError {}

/// A session lifecycle operation failed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SessionError {
    /// The session was already revoked and its fact cannot be rewritten.
    AlreadyRevoked,
    /// The requested time is inconsistent with the session timeline.
    InvalidTimeline,
}

impl From<SessionRestoreError> for SessionError {
    fn from(value: SessionRestoreError) -> Self {
        match value {
            SessionRestoreError::InvalidTimeline => Self::InvalidTimeline,
        }
    }
}

impl fmt::Display for SessionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AlreadyRevoked => formatter.write_str("session was already revoked"),
            Self::InvalidTimeline => {
                formatter.write_str("session timeline is inconsistent with its creation time")
            }
        }
    }
}

impl Error for SessionError {}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use time::Duration;

    use super::*;

    fn session_at(created_at: OffsetDateTime) -> Session {
        Session::new(
            SessionId::generate(),
            PrincipalId::generate(),
            [0x11; 32],
            [0x22; 32],
            created_at,
            created_at + Duration::hours(8),
        )
    }

    #[test]
    fn sessions_are_active_until_expiry_or_revocation() -> Result<(), Box<dyn Error>> {
        let created_at = OffsetDateTime::now_utc();
        let mut session = session_at(created_at);

        assert!(session.is_active(created_at + Duration::hours(1)));
        assert!(
            !session.is_active(created_at + Duration::hours(9)),
            "an expired session must be inactive"
        );

        session.revoke(created_at + Duration::hours(2))?;
        assert!(
            !session.is_active(created_at + Duration::hours(2)),
            "a revoked session must be inactive"
        );
        assert!(
            session.revoke(created_at + Duration::hours(3)) == Err(SessionError::AlreadyRevoked),
            "a second revocation must be refused"
        );
        assert_eq!(session.revoked_at(), Some(created_at + Duration::hours(2)));
        Ok(())
    }

    #[test]
    fn touch_advances_the_last_use_time() -> Result<(), Box<dyn Error>> {
        let created_at = OffsetDateTime::now_utc();
        let mut session = session_at(created_at);

        session.touch(created_at + Duration::hours(1))?;
        assert_eq!(session.last_used_at(), created_at + Duration::hours(1));
        assert!(
            session.touch(created_at) == Err(SessionRestoreError::InvalidTimeline),
            "activity cannot move the last use backwards"
        );
        Ok(())
    }

    #[test]
    fn rehydration_validates_the_timeline_and_round_trips() -> Result<(), Box<dyn Error>> {
        let created_at = OffsetDateTime::now_utc();
        let original = session_at(created_at);
        let mut revoked = original.clone();
        revoked.revoke(created_at + Duration::MINUTE)?;

        for session in [&original, &revoked] {
            let restored = Session::try_from_parts(
                session.id(),
                session.principal_id(),
                *session.token_hash(),
                *session.csrf_hash(),
                session.created_at(),
                session.last_used_at(),
                session.expires_at(),
                session.revoked_at(),
            )?;
            assert_eq!(restored, *session);
        }

        assert_eq!(
            Session::try_from_parts(
                original.id(),
                original.principal_id(),
                *original.token_hash(),
                *original.csrf_hash(),
                created_at,
                created_at,
                created_at,
                None,
            ),
            Err(SessionRestoreError::InvalidTimeline),
            "the expiry must follow the creation time"
        );
        assert_eq!(
            Session::try_from_parts(
                original.id(),
                original.principal_id(),
                *original.token_hash(),
                *original.csrf_hash(),
                created_at,
                created_at - Duration::SECOND,
                created_at + Duration::hours(8),
                None,
            ),
            Err(SessionRestoreError::InvalidTimeline),
            "the last use cannot precede the creation time"
        );
        assert_eq!(
            Session::try_from_parts(
                original.id(),
                original.principal_id(),
                *original.token_hash(),
                *original.csrf_hash(),
                created_at,
                created_at,
                created_at + Duration::hours(8),
                Some(created_at - Duration::SECOND),
            ),
            Err(SessionRestoreError::InvalidTimeline),
            "the revocation time cannot precede the creation time"
        );
        Ok(())
    }
}
