//! The product user model (§16 产品用户和权限).
//!
//! §16.1 scopes 1.0.0 to built-in product accounts with exactly three roles
//! — Administrator, Operator, Viewer — and no external identity sources
//! (LDAP/AD/OIDC/SAML/RADIUS are explicitly out). A [`Principal`] is one such
//! account: a normalized unique name and an enabled/disabled state. The
//! disabled state is a soft off switch: a disabled principal cannot sign in
//! and its sessions are revoked (§16.2 "密码或角色变化撤销旧 Session"), while
//! its rows — credentials, authenticators, assignments — stay intact so the
//! account can be re-enabled instead of re-created.
//!
//! A principal's role is a [`RoleAssignment`]: one row per principal, naming
//! the role, who assigned it (an optional principal id), and when. The
//! bootstrap flow (§16.2 "首次启动生成一次性 Bootstrap Code") is represented
//! by [`BootstrapCode`]: a one-time code that lets the initial administrator
//! claim the product and set the first password. The code is stored only as
//! its hash; the raw code is generated by the security crate and shown to the
//! operator exactly once.

use std::{error::Error, fmt, str::FromStr};

use time::OffsetDateTime;

use crate::{BootstrapCodeId, InstanceId, PrincipalId};

/// The longest principal name the product records, matching the
/// `principals.name` column width (64).
pub const MAX_PRINCIPAL_NAME_CHARS: usize = 64;

/// A normalized, unique product user name (§16.1).
///
/// Names are compared and stored in their normalized form: surrounding
/// whitespace trimmed and every letter lowercased, so `"Admin"`, `" admin "`
/// and `"admin"` are the same principal. The character set is bounded to
/// lowercase ASCII letters, digits, and the separators `.`, `-`, `_`, which
/// keeps the name safe to render in the §12.1 navigation and unambiguous in
/// audit records. The `principals.name` unique index makes the normalized
/// name the atomic duplicate refusal behind the persistence `create_principal`.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PrincipalName(String);

impl PrincipalName {
    /// Validates and normalizes a principal name.
    ///
    /// # Errors
    ///
    /// Returns [`PrincipalNameError`] when the name is empty, contains a
    /// character outside the allowed set, or exceeds
    /// [`MAX_PRINCIPAL_NAME_CHARS`] characters.
    pub fn parse(value: &str) -> Result<Self, PrincipalNameError> {
        let normalized = value.trim().to_lowercase();
        if normalized.is_empty() {
            return Err(PrincipalNameError::Empty);
        }
        let mut characters = normalized.chars();
        if !matches!(characters.next(), Some(first) if is_name_start(first)) {
            return Err(PrincipalNameError::InvalidCharacter);
        }
        if characters.any(|character| !is_name_character(character)) {
            return Err(PrincipalNameError::InvalidCharacter);
        }
        if normalized.chars().count() > MAX_PRINCIPAL_NAME_CHARS {
            return Err(PrincipalNameError::TooLong {
                maximum: MAX_PRINCIPAL_NAME_CHARS,
            });
        }
        Ok(Self(normalized))
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

fn is_name_start(character: char) -> bool {
    character.is_ascii_lowercase() || character.is_ascii_digit()
}

fn is_name_character(character: char) -> bool {
    is_name_start(character) || matches!(character, '.' | '-' | '_')
}

impl fmt::Display for PrincipalName {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl FromStr for PrincipalName {
    type Err = PrincipalNameError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::parse(value)
    }
}

/// Why a principal name cannot be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PrincipalNameError {
    Empty,
    InvalidCharacter,
    TooLong { maximum: usize },
}

impl fmt::Display for PrincipalNameError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => formatter.write_str("principal name cannot be empty"),
            Self::InvalidCharacter => formatter.write_str(
                "principal name may only contain lowercase letters, digits, and '.', '-', '_'",
            ),
            Self::TooLong { maximum } => {
                write!(formatter, "principal name exceeds {maximum} characters")
            }
        }
    }
}

impl Error for PrincipalNameError {}

/// The enabled/disabled state of one principal (§16.1).
///
/// The codes are the stable persistence contract (`principals.state` CHECK
/// constraint), so a persisted code round-trips through this enum without
/// ever being interpreted as raw text.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum PrincipalState {
    Enabled,
    Disabled,
}

impl PrincipalState {
    /// Returns the stable product code used by persistence and protocols.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Enabled => "enabled",
            Self::Disabled => "disabled",
        }
    }
}

impl fmt::Display for PrincipalState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl FromStr for PrincipalState {
    type Err = PrincipalStateParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "enabled" => Ok(Self::Enabled),
            "disabled" => Ok(Self::Disabled),
            _ => Err(PrincipalStateParseError),
        }
    }
}

/// A persisted principal state is unknown to this product build.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PrincipalStateParseError;

impl fmt::Display for PrincipalStateParseError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("unknown principal state code")
    }
}

impl Error for PrincipalStateParseError {}

/// One product user principal (§16.1).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Principal {
    id: PrincipalId,
    name: PrincipalName,
    state: PrincipalState,
    created_at: OffsetDateTime,
    updated_at: OffsetDateTime,
}

impl Principal {
    /// Declares a new enabled principal.
    ///
    /// The caller supplies the clock, keeping the domain free of clock access
    /// (§7.2). The update time equals the creation time until persistence
    /// records a state change.
    #[must_use]
    pub fn new(id: PrincipalId, name: PrincipalName, created_at: OffsetDateTime) -> Self {
        Self {
            id,
            name,
            state: PrincipalState::Enabled,
            created_at,
            updated_at: created_at,
        }
    }

    /// Rehydrates a persisted principal record.
    ///
    /// The database has no timeline constraint (mirroring the group and
    /// artifact precedents), so a stored row with an inverted timeline is
    /// refused here as a corrupt aggregate; the name is re-validated by its
    /// own type on the way in.
    ///
    /// # Errors
    ///
    /// Returns [`PrincipalRestoreError::InvalidTimeline`] when the stored
    /// update time precedes the stored creation time.
    pub fn try_from_parts(
        id: PrincipalId,
        name: PrincipalName,
        state: PrincipalState,
        created_at: OffsetDateTime,
        updated_at: OffsetDateTime,
    ) -> Result<Self, PrincipalRestoreError> {
        if updated_at < created_at {
            return Err(PrincipalRestoreError::InvalidTimeline);
        }
        Ok(Self {
            id,
            name,
            state,
            created_at,
            updated_at,
        })
    }

    /// Transitions the principal between enabled and disabled.
    ///
    /// Disabling is the soft-off switch of §16.1: the account stops signing
    /// in and its sessions are revoked, but its rows stay intact. Enabling
    /// restores it. The update time is recorded at the persistence boundary;
    /// the caller supplies the clock.
    pub fn set_state(&mut self, state: PrincipalState, at: OffsetDateTime) {
        self.state = state;
        self.updated_at = at;
    }

    #[must_use]
    pub const fn id(&self) -> PrincipalId {
        self.id
    }

    #[must_use]
    pub const fn name(&self) -> &PrincipalName {
        &self.name
    }

    #[must_use]
    pub const fn state(&self) -> PrincipalState {
        self.state
    }

    #[must_use]
    pub const fn created_at(&self) -> OffsetDateTime {
        self.created_at
    }

    #[must_use]
    pub const fn updated_at(&self) -> OffsetDateTime {
        self.updated_at
    }
}

/// A persisted principal record violates a domain invariant.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PrincipalRestoreError {
    /// The stored update time precedes the stored creation time.
    InvalidTimeline,
}

impl fmt::Display for PrincipalRestoreError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidTimeline => {
                formatter.write_str("principal update time cannot precede its creation time")
            }
        }
    }
}

impl Error for PrincipalRestoreError {}

/// A built-in product role (§16.1).
///
/// The codes are the stable persistence contract (`role_assignments.role`
/// CHECK constraint) and are also the vocabulary the §16.3 audit and the
/// future permission checks speak in.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Role {
    Administrator,
    Operator,
    Viewer,
}

impl Role {
    /// Returns the stable product code used by persistence and protocols.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Administrator => "administrator",
            Self::Operator => "operator",
            Self::Viewer => "viewer",
        }
    }
}

impl fmt::Display for Role {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl FromStr for Role {
    type Err = RoleParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "administrator" => Ok(Self::Administrator),
            "operator" => Ok(Self::Operator),
            "viewer" => Ok(Self::Viewer),
            _ => Err(RoleParseError),
        }
    }
}

/// A persisted role code is unknown to this product build.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RoleParseError;

impl fmt::Display for RoleParseError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("unknown role code")
    }
}

impl Error for RoleParseError {}

/// One principal's role assignment (§16.1).
///
/// The `role_assignments.principal_id` primary key means exactly one role per
/// principal; assigning a new role replaces the row. The assigner is an
/// optional principal id — a bootstrap-created assignment has no assigner —
/// and the database preserves the assigner as `SET NULL` when that principal
/// is later deleted, so the assignment fact never vanishes with its author.
///
/// A center role can be scoped to one site (D3: the `site_id` column). A
/// `site_id` of `None` is the global assignment — the role applies to every
/// site; a scoped assignment applies only to the named site (§16.1).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RoleAssignment {
    principal_id: PrincipalId,
    role: Role,
    assigned_by: Option<PrincipalId>,
    assigned_at: OffsetDateTime,
    site_id: Option<InstanceId>,
}

impl RoleAssignment {
    #[must_use]
    pub const fn new(
        principal_id: PrincipalId,
        role: Role,
        assigned_by: Option<PrincipalId>,
        assigned_at: OffsetDateTime,
        site_id: Option<InstanceId>,
    ) -> Self {
        Self {
            principal_id,
            role,
            assigned_by,
            assigned_at,
            site_id,
        }
    }

    #[must_use]
    pub const fn principal_id(&self) -> PrincipalId {
        self.principal_id
    }

    #[must_use]
    pub const fn role(&self) -> Role {
        self.role
    }

    #[must_use]
    pub const fn assigned_by(&self) -> Option<PrincipalId> {
        self.assigned_by
    }

    #[must_use]
    pub const fn assigned_at(&self) -> OffsetDateTime {
        self.assigned_at
    }

    /// The site this assignment is scoped to (D3, §16.1); `None` is the
    /// global assignment.
    #[must_use]
    pub const fn site_id(&self) -> Option<InstanceId> {
        self.site_id
    }
}

/// A one-time bootstrap code (§16.2).
///
/// First startup generates one bootstrap code so the initial administrator
/// can claim the product and set the first password ("首次启动生成一次性
/// Bootstrap Code"). Only the SHA-256 hash of the code is persisted; the raw
/// code is shown to the operator exactly once by the security crate. A code
/// is either unused or consumed exactly once: [`BootstrapCode::consume`]
/// refuses a second consumption, and the persistence `consume_bootstrap_code`
/// enforces the same rule atomically in its transaction.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BootstrapCode {
    id: BootstrapCodeId,
    code_hash: [u8; 32],
    created_at: OffsetDateTime,
    used_at: Option<OffsetDateTime>,
    used_by: Option<PrincipalId>,
}

impl BootstrapCode {
    /// Declares a new unused bootstrap code.
    #[must_use]
    pub fn new(id: BootstrapCodeId, code_hash: [u8; 32], created_at: OffsetDateTime) -> Self {
        Self {
            id,
            code_hash,
            created_at,
            used_at: None,
            used_by: None,
        }
    }

    /// Rehydrates a persisted bootstrap code record.
    ///
    /// # Errors
    ///
    /// Returns [`BootstrapCodeError::InvalidCodeHash`] when the stored hash
    /// is not exactly 32 bytes, or [`BootstrapCodeError::InvalidConsumption`]
    /// when exactly one of `used_at` and `used_by` is present.
    pub fn try_from_parts(
        id: BootstrapCodeId,
        code_hash: &[u8],
        created_at: OffsetDateTime,
        used_at: Option<OffsetDateTime>,
        used_by: Option<PrincipalId>,
    ) -> Result<Self, BootstrapCodeError> {
        let code_hash =
            <[u8; 32]>::try_from(code_hash).map_err(|_| BootstrapCodeError::InvalidCodeHash)?;
        if used_at.is_some() != used_by.is_some() {
            return Err(BootstrapCodeError::InvalidConsumption);
        }
        Ok(Self {
            id,
            code_hash,
            created_at,
            used_at,
            used_by,
        })
    }

    /// Consumes this code for one principal.
    ///
    /// # Errors
    ///
    /// Returns [`BootstrapCodeError::AlreadyUsed`] when the code was already
    /// consumed. The persistence layer repeats this check inside its consume
    /// transaction, so two racing consumers cannot both claim one code.
    pub fn consume(
        &mut self,
        used_by: PrincipalId,
        at: OffsetDateTime,
    ) -> Result<(), BootstrapCodeError> {
        if self.used_at.is_some() {
            return Err(BootstrapCodeError::AlreadyUsed);
        }
        self.used_at = Some(at);
        self.used_by = Some(used_by);
        Ok(())
    }

    #[must_use]
    pub const fn id(&self) -> BootstrapCodeId {
        self.id
    }

    #[must_use]
    pub const fn code_hash(&self) -> &[u8; 32] {
        &self.code_hash
    }

    #[must_use]
    pub const fn created_at(&self) -> OffsetDateTime {
        self.created_at
    }

    #[must_use]
    pub const fn used_at(&self) -> Option<OffsetDateTime> {
        self.used_at
    }

    #[must_use]
    pub const fn used_by(&self) -> Option<PrincipalId> {
        self.used_by
    }
}

/// Why a bootstrap code cannot be rehydrated or consumed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BootstrapCodeError {
    InvalidCodeHash,
    InvalidConsumption,
    AlreadyUsed,
}

impl fmt::Display for BootstrapCodeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidCodeHash => formatter.write_str("bootstrap code hash must be 32 bytes"),
            Self::InvalidConsumption => formatter.write_str(
                "bootstrap code consumption must record both the time and the principal",
            ),
            Self::AlreadyUsed => formatter.write_str("bootstrap code was already consumed"),
        }
    }
}

impl Error for BootstrapCodeError {}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use time::Duration;

    use super::*;

    #[test]
    fn name_validation_normalizes_lowercase_and_rejects_bad_names() -> Result<(), Box<dyn Error>> {
        assert_eq!(
            PrincipalName::parse("  Admin ")?,
            PrincipalName::parse("admin")?
        );
        assert_eq!(
            PrincipalName::parse("First.Admin-1")?.as_str(),
            "first.admin-1"
        );
        assert_eq!(
            PrincipalName::parse("admin")?,
            PrincipalName::parse("ADMIN")?
        );
        assert_eq!(PrincipalName::parse("  "), Err(PrincipalNameError::Empty));
        assert_eq!(
            PrincipalName::parse("adm in"),
            Err(PrincipalNameError::InvalidCharacter)
        );
        assert_eq!(
            PrincipalName::parse("-admin"),
            Err(PrincipalNameError::InvalidCharacter)
        );
        assert_eq!(
            PrincipalName::parse("admin名字"),
            Err(PrincipalNameError::InvalidCharacter)
        );
        assert!(matches!(
            PrincipalName::parse(&"a".repeat(MAX_PRINCIPAL_NAME_CHARS + 1)),
            Err(PrincipalNameError::TooLong { .. })
        ));
        Ok(())
    }

    #[test]
    fn principal_state_and_role_codes_round_trip() {
        for state in [PrincipalState::Enabled, PrincipalState::Disabled] {
            assert_eq!(state.to_string().parse::<PrincipalState>(), Ok(state));
        }
        assert_eq!(
            "banned".parse::<PrincipalState>(),
            Err(PrincipalStateParseError)
        );
        for role in [Role::Administrator, Role::Operator, Role::Viewer] {
            assert_eq!(role.to_string().parse::<Role>(), Ok(role));
        }
        assert_eq!("superuser".parse::<Role>(), Err(RoleParseError));
    }

    #[test]
    fn principal_lifecycle_tracks_state_and_time() -> Result<(), Box<dyn Error>> {
        let created_at = OffsetDateTime::now_utc();
        let mut principal = Principal::new(
            PrincipalId::generate(),
            PrincipalName::parse("admin")?,
            created_at,
        );

        assert_eq!(principal.state(), PrincipalState::Enabled);
        assert_eq!(principal.updated_at(), created_at);

        let disabled_at = created_at + Duration::SECOND;
        principal.set_state(PrincipalState::Disabled, disabled_at);
        assert_eq!(principal.state(), PrincipalState::Disabled);
        assert_eq!(principal.updated_at(), disabled_at);

        let restored = Principal::try_from_parts(
            principal.id(),
            principal.name().clone(),
            principal.state(),
            principal.created_at(),
            principal.updated_at(),
        )?;
        assert_eq!(restored, principal);
        assert_eq!(
            Principal::try_from_parts(
                principal.id(),
                principal.name().clone(),
                principal.state(),
                created_at,
                created_at - Duration::SECOND,
            ),
            Err(PrincipalRestoreError::InvalidTimeline)
        );
        Ok(())
    }

    #[test]
    fn role_assignment_carries_role_assigner_time_and_site_scope() {
        let assigned_by = PrincipalId::generate();
        let assigned_at = OffsetDateTime::now_utc();
        let assignment = RoleAssignment::new(
            PrincipalId::generate(),
            Role::Operator,
            Some(assigned_by),
            assigned_at,
            None,
        );

        assert_eq!(assignment.role(), Role::Operator);
        assert_eq!(assignment.assigned_by(), Some(assigned_by));
        assert_eq!(assignment.assigned_at(), assigned_at);
        assert_eq!(assignment.site_id(), None);
        // A D3 site-scoped assignment names exactly one site.
        let site = InstanceId::generate();
        let scoped = RoleAssignment::new(
            PrincipalId::generate(),
            Role::Viewer,
            None,
            assigned_at,
            Some(site),
        );
        assert_eq!(scoped.site_id(), Some(site));
        assert_eq!(
            RoleAssignment::new(
                PrincipalId::generate(),
                Role::Viewer,
                None,
                assigned_at,
                None
            )
            .assigned_by(),
            None
        );
    }

    #[test]
    fn bootstrap_code_is_consumed_exactly_once() -> Result<(), Box<dyn Error>> {
        let created_at = OffsetDateTime::now_utc();
        let mut code = BootstrapCode::new(BootstrapCodeId::generate(), [0x7b; 32], created_at);

        assert!(code.used_at().is_none());
        let used_by = PrincipalId::generate();
        code.consume(used_by, created_at + Duration::SECOND)?;
        assert_eq!(code.used_at(), Some(created_at + Duration::SECOND));
        assert_eq!(code.used_by(), Some(used_by));
        assert_eq!(
            code.consume(PrincipalId::generate(), created_at + Duration::SECOND * 2),
            Err(BootstrapCodeError::AlreadyUsed)
        );

        let restored = BootstrapCode::try_from_parts(
            code.id(),
            code.code_hash(),
            code.created_at(),
            code.used_at(),
            code.used_by(),
        )?;
        assert_eq!(restored, code);
        assert_eq!(
            BootstrapCode::try_from_parts(
                code.id(),
                &[0x7b; 31],
                code.created_at(),
                code.used_at(),
                code.used_by(),
            ),
            Err(BootstrapCodeError::InvalidCodeHash)
        );
        assert_eq!(
            BootstrapCode::try_from_parts(
                code.id(),
                code.code_hash(),
                code.created_at(),
                Some(created_at),
                None,
            ),
            Err(BootstrapCodeError::InvalidConsumption)
        );
        Ok(())
    }
}
