//! The Center's certificate authority (design §15, 0.7.0 S3b).
//!
//! The center generates one self-signed CA at first startup and persists
//! it below the data directory's `tls/` folder (`center-ca.crt` and
//! `center-ca.key`, the key mode 0600), so the CA identity survives
//! restarts and every issued certificate stays verifiable. The CA signs:
//!
//! * the center's own server certificate (`center-cert.pem` +
//!   `center-key.pem`, issued for the listen address and persisted by the
//!   acceptor) — the certificate whose SHA-256 fingerprint the operator
//!   pins on the site side (§10.4 explicit trust);
//! * one client certificate per bound site ([`CenterCa::issue_site_certificate`]),
//!   with the site instance id as the subject common name and the site's
//!   own identity fingerprint bound into the product's private-arc
//!   site-identity extension, so the issued certificate is cryptographically
//!   tied to the site instance that requested it.
//!
//! The client certificate's private key is generated by the center and
//! returned to the caller for delivery to the site (the one-time binding
//! flow); the center never persists a site's private key.

use std::{io, time::Duration};

use rcgen::{
    BasicConstraints, CertificateParams, DnType, ExtendedKeyUsagePurpose, IsCa, Issuer, KeyPair,
    KeyUsagePurpose, PKCS_ECDSA_P256_SHA256,
};
use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer};
use rutilus_domain::{CertificateFingerprint, InstanceId};
use rutilus_platform::RuntimePaths;
use thiserror::Error;
use time::OffsetDateTime;

use crate::{
    ListenAddress,
    tls_material::{
        TlsMaterialError, pem_encode, persist_text, read_certificate, read_private_key,
    },
    x509,
};

/// The subject common name of the center CA certificate.
const CENTER_CA_COMMON_NAME: &str = "Rutilus Center CA";

/// The persisted CA file names below the data directory's `tls/` folder.
const CENTER_CA_CERT_FILE: &str = "center-ca.crt";
const CENTER_CA_KEY_FILE: &str = "center-ca.key";

/// Certificate validity windows. The CA lives a decade, like the Site's
/// self-signed pair; the issued certificates live five years. The
/// one-day lookback absorbs clock skew at verification time.
// `Duration::from_days` is not stable in this toolchain, so the day
// multiples below are spelled out in seconds.
#[allow(clippy::duration_suboptimal_units)]
const CA_VALIDITY: Duration = Duration::from_secs(60 * 60 * 24 * 365 * 10);
#[allow(clippy::duration_suboptimal_units)]
const ISSUED_VALIDITY: Duration = Duration::from_secs(60 * 60 * 24 * 365 * 5);
#[allow(clippy::duration_suboptimal_units)]
const NOT_BEFORE_SKEW: Duration = Duration::from_secs(60 * 60 * 24);

/// The center certificate authority: the signing key pair, the CA
/// certificate, and its SHA-256 fingerprint.
#[derive(Debug)]
pub struct CenterCa {
    key_pair: KeyPair,
    certificate: CertificateDer<'static>,
    fingerprint: CertificateFingerprint,
}

impl CenterCa {
    /// Loads the persisted CA pair below `<data>/tls/`, or generates and
    /// persists a fresh CA (the private key mode 0600). A half-written
    /// pair — one file present, the other missing — is a hard error, never
    /// silently regenerated.
    ///
    /// # Errors
    ///
    /// Returns [`CenterCaError`] for unreadable or invalid PEM material,
    /// generation failure, or persistence failure.
    pub fn generate_or_load(paths: &RuntimePaths) -> Result<Self, CenterCaError> {
        let certificate_path = paths.tls_directory().join(CENTER_CA_CERT_FILE);
        let key_path = paths.tls_directory().join(CENTER_CA_KEY_FILE);
        match (
            read_certificate(&certificate_path),
            read_private_key(&key_path),
        ) {
            // A previously generated CA is reused so the center keeps its
            // signing identity — and every issued certificate's validity —
            // across restarts; a missing pair is generated fresh.
            (Ok(certificate), Ok(key)) => Self::from_material(certificate, key),
            (Err(cert_error), Err(key_error))
                if is_missing(&cert_error) && is_missing(&key_error) =>
            {
                Self::generate_and_persist(paths)
            }
            (Err(cert_error), Err(key_error)) => Err(CenterCaError::ReadPair {
                cert_error: Box::new(cert_error),
                key_error: Box::new(key_error),
            }),
            (Err(error), Ok(_)) | (Ok(_), Err(error)) => Err(error.into()),
        }
    }

    /// The CA certificate: the trust anchor of every certificate this
    /// center issues.
    #[must_use]
    pub fn certificate(&self) -> CertificateDer<'static> {
        self.certificate.clone()
    }

    /// The SHA-256 fingerprint of the CA certificate, in the product's
    /// colon-separated uppercase hex format.
    #[must_use]
    pub const fn fingerprint(&self) -> CertificateFingerprint {
        self.fingerprint
    }

    /// Issues one client certificate for a bound site (design §15.1,
    /// one-time binding): the site instance id as the subject common name,
    /// the `clientAuth` extended key usage, and the site's own identity
    /// fingerprint bound into the site-identity extension. The private key
    /// is generated here and returned with the certificate for delivery to
    /// the site; it is never persisted by the center.
    ///
    /// # Errors
    ///
    /// Returns [`CenterCaError`] when the CA subject cannot be read back
    /// for signing, or key or certificate generation fails.
    pub fn issue_site_certificate(
        &self,
        site: InstanceId,
        site_fingerprint: CertificateFingerprint,
    ) -> Result<SiteClientCertificate, CenterCaError> {
        let mut params = issued_certificate_params(&site.to_string())?;
        params.extended_key_usages = vec![ExtendedKeyUsagePurpose::ClientAuth];
        params.key_usages = vec![KeyUsagePurpose::DigitalSignature];
        params
            .custom_extensions
            .push(site_identity_extension(site_fingerprint)?);
        let key_pair = KeyPair::generate().map_err(CenterCaError::GenerateKey)?;
        let certificate = params
            .signed_by(&key_pair, &self.issuer()?)
            .map_err(CenterCaError::Generate)?;
        Ok(SiteClientCertificate::new(
            certificate.der().clone(),
            &key_pair,
        ))
    }

    /// Issues the center's own server certificate for one listen address:
    /// the SAN covers the listen host, the `serverAuth` extended key
    /// usage, and the chain roots at this CA — so a site whose trust
    /// anchor is this CA verifies the center, and the operator's pin of
    /// the server certificate fingerprint is the explicit trust decision
    /// (§10.4).
    ///
    /// # Errors
    ///
    /// Returns [`CenterCaError`] when the CA subject cannot be read back
    /// for signing, or key or certificate generation fails.
    pub(crate) fn issue_server_certificate(
        &self,
        listen: &ListenAddress,
    ) -> Result<ServerCertificate, CenterCaError> {
        let mut params = issued_certificate_params(&listen.to_string())?;
        if let Some(ip) = listen.ip() {
            params.subject_alt_names.push(rcgen::SanType::IpAddress(ip));
        } else {
            let name = rcgen::string::Ia5String::try_from(listen.host())
                .map_err(CenterCaError::Generate)?;
            params.subject_alt_names.push(rcgen::SanType::DnsName(name));
        }
        params.extended_key_usages = vec![ExtendedKeyUsagePurpose::ServerAuth];
        params.key_usages = vec![
            KeyUsagePurpose::DigitalSignature,
            KeyUsagePurpose::KeyEncipherment,
        ];
        let key_pair = KeyPair::generate().map_err(CenterCaError::GenerateKey)?;
        let certificate = params
            .signed_by(&key_pair, &self.issuer()?)
            .map_err(CenterCaError::Generate)?;
        Ok(ServerCertificate {
            certificate: certificate.der().clone(),
            key: PrivatePkcs8KeyDer::from(key_pair.serialize_der()).into(),
        })
    }

    fn from_material(
        certificate: CertificateDer<'static>,
        key: PrivateKeyDer<'static>,
    ) -> Result<Self, CenterCaError> {
        let PrivateKeyDer::Pkcs8(pkcs8) = key else {
            return Err(CenterCaError::UnsupportedKeyFormat);
        };
        let key_pair = KeyPair::from_pkcs8_der_and_sign_algo(&pkcs8, &PKCS_ECDSA_P256_SHA256)
            .map_err(CenterCaError::SigningKey)?;
        let fingerprint = CertificateFingerprint::from_certificate_der(certificate.as_ref());
        Ok(Self {
            key_pair,
            certificate,
            fingerprint,
        })
    }

    fn generate_and_persist(paths: &RuntimePaths) -> Result<Self, CenterCaError> {
        let key_pair = KeyPair::generate().map_err(CenterCaError::GenerateKey)?;
        let mut params =
            CertificateParams::new(Vec::<String>::new()).map_err(CenterCaError::Generate)?;
        params
            .distinguished_name
            .push(DnType::CommonName, CENTER_CA_COMMON_NAME);
        params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
        params.key_usages = vec![KeyUsagePurpose::KeyCertSign, KeyUsagePurpose::CrlSign];
        set_validity(&mut params, CA_VALIDITY);
        let certificate = params
            .self_signed(&key_pair)
            .map_err(CenterCaError::Generate)?;
        let certificate = certificate.der().clone();
        let fingerprint = CertificateFingerprint::from_certificate_der(certificate.as_ref());
        let certificate_path = paths.tls_directory().join(CENTER_CA_CERT_FILE);
        let key_path = paths.tls_directory().join(CENTER_CA_KEY_FILE);
        persist_text(
            &certificate_path,
            &pem_encode("CERTIFICATE", certificate.as_ref()),
        )?;
        persist_text(
            &key_path,
            &pem_encode("PRIVATE KEY", &key_pair.serialize_der()),
        )?;
        Ok(Self {
            key_pair,
            certificate,
            fingerprint,
        })
    }

    /// The signing issuer: the CA's subject and key. The subject is read
    /// back from the CA certificate (which is the source of truth on every
    /// boot, including a loaded CA) and must be exactly the single common
    /// name this product writes; anything else is refused rather than
    /// signed with.
    fn issuer(&self) -> Result<Issuer<'static, &KeyPair>, CenterCaError> {
        let attributes =
            x509::subject_attributes(&self.certificate).map_err(CenterCaError::Certificate)?;
        let [attribute] = attributes.as_slice() else {
            return Err(CenterCaError::CaSubjectUnsupported);
        };
        if attribute.oid.as_slice() != x509::CN_OID {
            return Err(CenterCaError::CaSubjectUnsupported);
        }
        let mut params =
            CertificateParams::new(Vec::<String>::new()).map_err(CenterCaError::Generate)?;
        params
            .distinguished_name
            .push(DnType::CommonName, attribute.value.as_str());
        Ok(Issuer::new(params, &self.key_pair))
    }
}

fn is_missing(error: &TlsMaterialError) -> bool {
    matches!(
        error,
        TlsMaterialError::ReadFile { source, .. } if source.kind() == io::ErrorKind::NotFound
    )
}

/// The common parameters of every issued certificate: validity window,
/// and the authority key identifier of the signing CA.
fn issued_certificate_params(subject: &str) -> Result<CertificateParams, CenterCaError> {
    let mut params =
        CertificateParams::new(Vec::<String>::new()).map_err(CenterCaError::Generate)?;
    params.distinguished_name.push(DnType::CommonName, subject);
    set_validity(&mut params, ISSUED_VALIDITY);
    Ok(params)
}

fn set_validity(params: &mut CertificateParams, validity: Duration) {
    let now = OffsetDateTime::now_utc();
    params.not_before = now - NOT_BEFORE_SKEW;
    params.not_after = now + validity;
}

/// The site-identity extension: the product's private-arc OID carrying the
/// DER encoding of one OCTET STRING that wraps the site fingerprint bytes.
/// rcgen's `CustomExtension` contract requires the content to be DER, and
/// it is written verbatim into the extension's `extnValue` OCTET STRING.
fn site_identity_extension(
    site_fingerprint: CertificateFingerprint,
) -> Result<rcgen::CustomExtension, CenterCaError> {
    let bytes = site_fingerprint.as_bytes();
    let length = u8::try_from(bytes.len()).map_err(|_| CenterCaError::FingerprintTooLarge)?;
    let mut content = Vec::with_capacity(2 + bytes.len());
    content.push(0x04);
    content.push(length);
    content.extend_from_slice(bytes);
    Ok(rcgen::CustomExtension::from_oid_content(
        x509::SITE_IDENTITY_EXTENSION_OID,
        content,
    ))
}

/// The client certificate of one bound site, with the private key the
/// center generated for it.
///
/// Deliberately not `Debug`: the private key DER must never reach a log.
/// The key is stored as PKCS#8 bytes (the only encoding this product's
/// key generation produces); [`SiteClientCertificate::private_key`]
/// rebuilds a rustls key from those bytes on demand.
pub struct SiteClientCertificate {
    certificate: CertificateDer<'static>,
    key_pkcs8: Vec<u8>,
    fingerprint: CertificateFingerprint,
}

impl SiteClientCertificate {
    fn new(certificate: CertificateDer<'static>, key_pair: &KeyPair) -> Self {
        let fingerprint = CertificateFingerprint::from_certificate_der(certificate.as_ref());
        Self {
            certificate,
            key_pkcs8: key_pair.serialize_der(),
            fingerprint,
        }
    }

    /// The issued client certificate.
    #[must_use]
    pub fn certificate(&self) -> CertificateDer<'static> {
        self.certificate.clone()
    }

    /// The private key of the issued client certificate.
    #[must_use]
    pub fn private_key(&self) -> PrivateKeyDer<'static> {
        PrivatePkcs8KeyDer::from(self.key_pkcs8.clone()).into()
    }

    /// The SHA-256 fingerprint of the issued client certificate — the
    /// identity the center records in its binding and the acceptor maps
    /// back to the site instance.
    #[must_use]
    pub const fn fingerprint(&self) -> CertificateFingerprint {
        self.fingerprint
    }

    /// The certificate and private key as PEM texts, for delivery to the
    /// site (the one-time binding flow writes them below the site's
    /// `tls/` folder).
    #[must_use]
    pub fn pem_pair(&self) -> (String, String) {
        let certificate = pem_encode("CERTIFICATE", self.certificate.as_ref());
        let key = pem_encode("PRIVATE KEY", &self.key_pkcs8);
        (certificate, key)
    }
}

/// The center's own server certificate and key, issued by the center CA.
#[derive(Debug)]
pub(crate) struct ServerCertificate {
    pub(crate) certificate: CertificateDer<'static>,
    pub(crate) key: PrivateKeyDer<'static>,
}

/// A controlled failure while preparing or using the center CA.
#[derive(Debug, Error)]
pub enum CenterCaError {
    #[error("failed to prepare the center CA material: {0}")]
    Material(#[from] TlsMaterialError),
    #[error("failed to read the center CA pair ({cert_error}; {key_error})")]
    ReadPair {
        cert_error: Box<TlsMaterialError>,
        key_error: Box<TlsMaterialError>,
    },
    #[error("the center CA private key is not a PKCS#8 key")]
    UnsupportedKeyFormat,
    #[error("the center CA certificate cannot be read: {0}")]
    Certificate(#[from] x509::DerReadError),
    #[error("the center CA subject is not the single common name this product signs with")]
    CaSubjectUnsupported,
    #[error("failed to generate a center key pair: {0}")]
    GenerateKey(#[source] rcgen::Error),
    #[error("failed to load the center CA signing key: {0}")]
    SigningKey(#[source] rcgen::Error),
    #[error("failed to generate a center certificate: {0}")]
    Generate(#[source] rcgen::Error),
    #[error("the site identity fingerprint does not fit the extension encoding")]
    FingerprintTooLarge,
}

#[cfg(test)]
mod tests {
    use std::{error::Error, io, sync::Arc};

    use rustls::{
        RootCertStore, ServerConfig,
        client::ClientConnection,
        pki_types::{CertificateDer, ServerName, pem::PemObject as _},
        server::{ServerConnection, WebPkiClientVerifier},
    };
    use rutilus_platform::RuntimePaths;

    use super::*;

    #[test]
    fn generates_persists_and_reuses_the_ca() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;

        let first = CenterCa::generate_or_load(&paths)?;
        assert_eq!(first.fingerprint().to_string().split(':').count(), 32);
        assert!(paths.tls_directory().join("center-ca.crt").is_file());
        assert!(paths.tls_directory().join("center-ca.key").is_file());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(paths.tls_directory().join("center-ca.key"))?
                .permissions()
                .mode()
                & 0o777;
            assert_eq!(mode, 0o600);
        }

        // A second boot reuses the persisted CA identity.
        let second = CenterCa::generate_or_load(&paths)?;
        assert_eq!(first.fingerprint(), second.fingerprint());
        assert_eq!(first.certificate(), second.certificate());
        Ok(())
    }

    #[test]
    fn a_half_written_ca_pair_is_a_hard_error() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;
        std::fs::create_dir_all(paths.tls_directory())?;
        // A certificate file without its key: the pair is broken and must
        // never be silently regenerated.
        std::fs::write(
            paths.tls_directory().join("center-ca.crt"),
            "not a pem certificate",
        )?;

        assert!(matches!(
            CenterCa::generate_or_load(&paths),
            Err(CenterCaError::ReadPair { .. })
        ));
        Ok(())
    }

    #[test]
    fn issues_client_certificates_with_the_site_identity() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;
        let ca = CenterCa::generate_or_load(&paths)?;
        let site = InstanceId::generate();
        let site_fingerprint = CertificateFingerprint::from_bytes([0xAB; 32]);

        let issued = ca.issue_site_certificate(site, site_fingerprint)?;
        assert_eq!(issued.fingerprint().to_string().split(':').count(), 32);
        assert_eq!(
            x509::subject_common_name(&issued.certificate())?,
            Some(site.to_string())
        );
        assert_eq!(
            x509::site_identity_fingerprint(&issued.certificate())?,
            Some(site_fingerprint)
        );
        // The PEM pair round-trips through the same readers the site uses.
        let (cert_pem, key_pem) = issued.pem_pair();
        let certificate = CertificateDer::from_pem_slice(cert_pem.as_bytes())?;
        let key = PrivateKeyDer::from_pem_slice(key_pem.as_bytes())?;
        assert_eq!(certificate, issued.certificate());
        assert_eq!(key, issued.private_key());
        Ok(())
    }

    /// Runs one full TLS handshake in memory between a client and a server
    /// connection, without sockets, by shuttling each side's write buffer
    /// into the other side's read buffer until neither side is handshaking.
    /// A stalled or failed handshake returns an error instead of looping.
    fn handshake(
        client: &mut ClientConnection,
        server: &mut ServerConnection,
    ) -> Result<(), Box<dyn Error>> {
        let mut buffer = Vec::new();
        for _ in 0..64 {
            let wrote = client.wants_write() || server.wants_write();
            while client.wants_write() {
                buffer.clear();
                client.write_tls(&mut buffer)?;
                server.read_tls(&mut buffer.as_slice())?;
            }
            while server.wants_write() {
                buffer.clear();
                server.write_tls(&mut buffer)?;
                client.read_tls(&mut buffer.as_slice())?;
            }
            client.process_new_packets()?;
            server.process_new_packets()?;
            if !client.is_handshaking() && !server.is_handshaking() {
                return Ok(());
            }
            if !wrote && !client.wants_write() && !server.wants_write() {
                return Err(io::Error::other("the in-memory TLS handshake stalled").into());
            }
        }
        Err(io::Error::other("the in-memory TLS handshake did not complete").into())
    }

    /// A server configuration that requires a client certificate rooted at
    /// the given CA, serving a CA-issued certificate for 127.0.0.1.
    fn verifier_server_config(
        ca: &CenterCa,
        server_identity: ServerCertificate,
    ) -> Result<Arc<ServerConfig>, Box<dyn Error>> {
        let mut roots = RootCertStore::empty();
        roots.add(ca.certificate())?;
        let verifier = WebPkiClientVerifier::builder(Arc::new(roots)).build()?;
        let provider = Arc::new(rustls::crypto::ring::default_provider());
        let config = ServerConfig::builder_with_provider(provider)
            .with_protocol_versions(&[&rustls::version::TLS13])?
            .with_client_cert_verifier(verifier)
            .with_single_cert(vec![server_identity.certificate], server_identity.key)?;
        Ok(Arc::new(config))
    }

    fn verifier_client_config(
        ca: &CenterCa,
        identity: Option<(CertificateDer<'static>, PrivateKeyDer<'static>)>,
    ) -> Result<Arc<rustls::ClientConfig>, Box<dyn Error>> {
        let mut roots = RootCertStore::empty();
        roots.add(ca.certificate())?;
        let provider = Arc::new(rustls::crypto::ring::default_provider());
        let builder = rustls::ClientConfig::builder_with_provider(provider)
            .with_protocol_versions(&[&rustls::version::TLS13])?;
        let config = match identity {
            Some((certificate, key)) => builder
                .with_root_certificates(roots)
                .with_client_auth_cert(vec![certificate], key)?,
            None => builder.with_root_certificates(roots).with_no_client_auth(),
        };
        Ok(Arc::new(config))
    }

    #[tokio::test]
    async fn issued_client_certificates_verify_against_the_ca() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;
        let ca = CenterCa::generate_or_load(&paths)?;
        let listen = crate::ListenAddress::parse("127.0.0.1:8443")?;
        let server_identity = ca.issue_server_certificate(&listen)?;
        let site = InstanceId::generate();
        let issued =
            ca.issue_site_certificate(site, CertificateFingerprint::from_bytes([0xCD; 32]))?;

        let server_config = verifier_server_config(&ca, server_identity)?;
        let client_config =
            verifier_client_config(&ca, Some((issued.certificate(), issued.private_key())))?;
        let mut client = ClientConnection::new(client_config, ServerName::try_from("127.0.0.1")?)?;
        let mut server = ServerConnection::new(server_config)?;
        handshake(&mut client, &mut server)?;

        // The server saw the issued certificate, fingerprint and all.
        let presented = server
            .peer_certificates()
            .ok_or_else(|| io::Error::other("no peer certificate"))?;
        let presented = presented
            .first()
            .ok_or_else(|| io::Error::other("empty peer chain"))?;
        assert_eq!(
            CertificateFingerprint::from_certificate_der(presented.as_ref()),
            issued.fingerprint()
        );
        Ok(())
    }

    #[tokio::test]
    async fn a_client_without_a_certificate_is_refused() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;
        let ca = CenterCa::generate_or_load(&paths)?;
        let listen = crate::ListenAddress::parse("127.0.0.1:8443")?;
        let server_identity = ca.issue_server_certificate(&listen)?;
        let server_config = verifier_server_config(&ca, server_identity)?;
        let client_config = verifier_client_config(&ca, None)?;
        let mut client = ClientConnection::new(client_config, ServerName::try_from("127.0.0.1")?)?;
        let mut server = ServerConnection::new(server_config)?;
        assert!(handshake(&mut client, &mut server).is_err());
        Ok(())
    }

    #[tokio::test]
    async fn a_certificate_from_an_unknown_ca_is_refused() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;
        let ca = CenterCa::generate_or_load(&paths)?;
        let foreign_directory = tempfile::tempdir()?;
        let foreign_paths = RuntimePaths::from_root(foreign_directory.path().join("instance"))?;
        let foreign_ca = CenterCa::generate_or_load(&foreign_paths)?;
        let foreign_issued = foreign_ca.issue_site_certificate(
            InstanceId::generate(),
            CertificateFingerprint::from_bytes([0xEE; 32]),
        )?;
        let listen = crate::ListenAddress::parse("127.0.0.1:8443")?;
        let server_identity = ca.issue_server_certificate(&listen)?;

        let server_config = verifier_server_config(&ca, server_identity)?;
        // The client trusts the first CA but presents a certificate from
        // the second CA: the chain cannot root at the verifier's anchor.
        let client_config = verifier_client_config(
            &ca,
            Some((foreign_issued.certificate(), foreign_issued.private_key())),
        )?;
        let mut client = ClientConnection::new(client_config, ServerName::try_from("127.0.0.1")?)?;
        let mut server = ServerConnection::new(server_config)?;
        assert!(handshake(&mut client, &mut server).is_err());
        Ok(())
    }

    #[tokio::test]
    async fn a_reloaded_ca_keeps_issuing_verifiable_certificates() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let paths = RuntimePaths::from_root(directory.path().join("instance"))?;
        let first = CenterCa::generate_or_load(&paths)?;
        let first_issued = first.issue_site_certificate(
            InstanceId::generate(),
            CertificateFingerprint::from_bytes([0x11; 32]),
        )?;
        // The loaded CA must rebuild its signing issuer from the persisted
        // certificate — the subject read-back path.
        let reloaded = CenterCa::generate_or_load(&paths)?;
        let reloaded_issued = reloaded.issue_site_certificate(
            InstanceId::generate(),
            CertificateFingerprint::from_bytes([0x22; 32]),
        )?;

        let listen = crate::ListenAddress::parse("127.0.0.1:8443")?;
        let server_identity = reloaded.issue_server_certificate(&listen)?;
        let server_config = verifier_server_config(&reloaded, server_identity)?;
        for issued in [&first_issued, &reloaded_issued] {
            let client_config = verifier_client_config(
                &reloaded,
                Some((issued.certificate(), issued.private_key())),
            )?;
            let mut client =
                ClientConnection::new(client_config, ServerName::try_from("127.0.0.1")?)?;
            let mut server = ServerConnection::new(Arc::clone(&server_config))?;
            let completed = handshake(&mut client, &mut server);
            assert!(
                completed.is_ok(),
                "certificate {} must verify against the reloaded CA",
                issued.fingerprint()
            );
        }
        Ok(())
    }
}
