//! Protobuf wire types generated by `prost-build` from
//! `proto/rutilus/center/v1/center.proto`. Do not edit by hand; change the
//! `.proto` file and re-run the build.
//!
//! `prost` 0.14 writes one file per proto package into `OUT_DIR` and does
//! not ship the `include_proto!` macro from the 0.7.0 design draft; the
//! canonical 0.14 pattern nests the package modules by hand and `include!`
//! the per-package file inside them.
//!
//! The clippy allows cover `prost`'s own generated documentation and
//! helpers, which are outside the control of this crate: `ProtoBuf` in the
//! trait docs (`doc_markdown`), `as_str_name`/`from_str_name` without
//! `#[must_use]` (`must_use_candidate`), and message structs deriving
//! `PartialEq` without `Eq` (`derive_partial_eq_without_eq`; the lint sits
//! outside the workspace's deny groups today but is kept silenced so the
//! generated surface cannot regress the gate).

#[allow(
    clippy::derive_partial_eq_without_eq,
    clippy::doc_markdown,
    clippy::must_use_candidate
)]
pub mod rutilus {
    pub mod center {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/rutilus.center.v1.rs"));
        }
    }
}
