#![forbid(unsafe_code)]

//! The Rutilus site-to-center wire protocol (design §8, §15).
//!
//! This crate carries exactly three things:
//!
//! * the Protobuf messages of §15.2 plus `NegotiationResult` (the fifteenth
//!   message added by the 0.7.0 design pass), generated by `prost-build`
//!   from `proto/rutilus/center/v1/center.proto` and re-exported below;
//! * the version-negotiation pure functions (`negotiate`,
//!   `capability_ledger_hash`);
//! * the protocol constants (`CENTER_PROTOCOL_VERSION`, frame and heartbeat
//!   limits, the pinned `NV_REDFISH_BASELINE`).
//!
//! The generated wire types are not wrapped: the wire type is the wire type
//! (design §7.2). The crate depends only on `rutilus-domain` (for the
//! stable capability codes the ledger hash is built from), `prost`, and
//! `sha2` (the ledger hash); it never touches `axum`, `tokio`, `SeaORM`, or
//! `nv-redfish`.

mod generated;
mod negotiation;

pub use generated::rutilus::center::v1::envelope::Message as EnvelopeMessage;
pub use generated::rutilus::center::v1::{
    Ack, ArtifactChunk, ArtifactManifest, CapabilityEntry, CapabilityManifest, CapabilityState,
    EndpointSnapshot, Envelope, EventBatch, EventRecord, EventSeverity, Heartbeat, Hello,
    NegotiationResult, OperationAccepted, OperationCompleted, OperationOffer, OperationProgress,
    OperationRejected, OperationRejectedReason, ResourceDelta, ResourceDeltaOp, ResourceSummary,
    TlsTrust,
};
pub use negotiation::{
    NegotiationDecision, NegotiationReason, NegotiationReasonParseError, capability_ledger_hash,
    negotiate,
};

use std::time::Duration;

/// The protocol version this crate implements (§15.3). Version 1 is the
/// wire contract defined by `proto/rutilus/center/v1/center.proto`; a peer
/// with any other `center_protocol_version` is rejected with
/// `protocol-mismatch`.
pub const CENTER_PROTOCOL_VERSION: u32 = 1;

/// The largest legal WebSocket binary frame, in bytes. Every frame carries
/// exactly one [`Envelope`]; 8 MiB bounds the buffered frames that a peer
/// may force a receiver to hold before it can decode the envelope.
pub const MAX_FRAME_BYTES: usize = 8 * 1024 * 1024;

/// How often a site sends a [`Heartbeat`] to its center: every 30 seconds.
pub const SITE_HEARTBEAT_INTERVAL: Duration = Duration::from_secs(30);

/// How long the center waits for a site frame before declaring the
/// connection dead: 90 seconds, three heartbeat intervals, so two missed
/// heartbeats are tolerated and the third triggers the disconnect.
pub const CENTER_DISCONNECT_AFTER: Duration = Duration::from_secs(90);

/// How long a site waits after a disconnect before attempting to reconnect:
/// 120 seconds, long enough for the center to have noticed the dead
/// connection and for a restarting center to be back on its feet.
// The 30/90/120-second family reads better in seconds; the seconds unit is
// intentional (see app/src/telemetry_sampler.rs for the same allowance).
#[allow(clippy::duration_suboptimal_units)]
pub const SITE_RECONNECT_AFTER: Duration = Duration::from_secs(120);

/// The pinned `nv-redfish` baseline of this product build (§2.3, §15.3).
/// The workspace `Cargo.toml` pins `nv-redfish` to `=0.13.0`; this string
/// must stay equal to that pin, and a peer whose `Hello` carries any other
/// baseline is rejected with `baseline-mismatch`.
pub const NV_REDFISH_BASELINE: &str = "0.13.0";

#[cfg(test)]
mod tests {
    use super::{
        CENTER_DISCONNECT_AFTER, CENTER_PROTOCOL_VERSION, MAX_FRAME_BYTES, NV_REDFISH_BASELINE,
        SITE_HEARTBEAT_INTERVAL, SITE_RECONNECT_AFTER,
    };
    use crate::{
        Ack, ArtifactChunk, ArtifactManifest, CapabilityEntry, CapabilityManifest, CapabilityState,
        EndpointSnapshot, Envelope, EnvelopeMessage, EventBatch, EventRecord, EventSeverity,
        Heartbeat, Hello, NegotiationResult, OperationAccepted, OperationCompleted, OperationOffer,
        OperationProgress, OperationRejected, OperationRejectedReason, ResourceDelta,
        ResourceDeltaOp, ResourceSummary, TlsTrust, capability_ledger_hash, negotiate,
    };
    use prost::Message;
    use std::fmt::Debug;
    use std::time::Duration;

    /// The wire format of every message must survive an encode/decode
    /// round trip with every field populated.
    fn assert_round_trip<T>(message: &T)
    where
        T: Message + PartialEq + Debug + Default,
    {
        let encoded = message.encode_to_vec();
        let decoded = T::decode(encoded.as_slice());
        assert_eq!(decoded.as_ref(), Ok(message));
    }

    pub(crate) fn sample_hello() -> Hello {
        Hello {
            product_version: String::from("0.7.0"),
            center_protocol_version: CENTER_PROTOCOL_VERSION,
            nv_redfish_baseline: String::from(NV_REDFISH_BASELINE),
            capability_ledger_hash: capability_ledger_hash().to_vec(),
            instance_id: String::from("site-1"),
            site_name: String::from("Site One"),
            last_acked_sequence: 42,
        }
    }

    fn sample_capability_manifest() -> CapabilityManifest {
        CapabilityManifest {
            capabilities: vec![
                CapabilityEntry {
                    code: String::from("chassis"),
                    state: CapabilityState::Advertised as i32,
                },
                CapabilityEntry {
                    code: String::from("power"),
                    state: CapabilityState::Usable as i32,
                },
            ],
            observed_at_unix: 1_700_000_000,
        }
    }

    fn sample_endpoint_snapshot() -> EndpointSnapshot {
        EndpointSnapshot {
            endpoint_id: String::from("endpoint-1"),
            display_name: String::from("Rack A PDU"),
            address: String::from("https://192.0.2.10"),
            trust: TlsTrust::PinnedCertificate as i32,
            refresh_generation: 3,
            resources: vec![ResourceSummary {
                feature: String::from("power"),
                odata_id: String::from("/redfish/v1/Power"),
                odata_type: String::from("#Power.v1_6_1.Power"),
                etag: String::from("\"abc123\""),
                generation: 3,
            }],
            health: String::from("ok"),
        }
    }

    fn sample_resource_delta() -> ResourceDelta {
        ResourceDelta {
            endpoint_id: String::from("endpoint-1"),
            op: ResourceDeltaOp::Upsert as i32,
            resource: Some(ResourceSummary {
                feature: String::from("power"),
                odata_id: String::from("/redfish/v1/Power"),
                odata_type: String::from("#Power.v1_6_1.Power"),
                etag: String::from("\"abc123\""),
                generation: 4,
            }),
            payload_json: b"{\"power\":\"on\"}".to_vec(),
            observed_at_unix: 1_700_000_010,
        }
    }

    fn sample_event_batch() -> EventBatch {
        EventBatch {
            events: vec![EventRecord {
                event_id: String::from("event-1"),
                message_id: String::from("ResourceEvent.1.0.ResourceUpdated"),
                severity: EventSeverity::Warning as i32,
                target: String::from("/redfish/v1/Systems/1"),
                occurred_at_unix: 1_700_000_020,
                payload_json: b"{\"message\":\"rebooted\"}".to_vec(),
            }],
        }
    }

    fn sample_operation_offer() -> OperationOffer {
        OperationOffer {
            operation_id: String::from("operation-1"),
            endpoint_id: String::from("endpoint-1"),
            site_id: String::from("site-1"),
            command_json: b"{\"command\":\"Reset\"}".to_vec(),
            target: String::from("/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"),
            expires_at_unix: 1_700_000_100,
            actor_context: String::from("principal-7"),
        }
    }

    fn sample_operation_rejected() -> OperationRejected {
        OperationRejected {
            operation_id: String::from("operation-1"),
            reason: OperationRejectedReason::TargetStateChanged as i32,
            detail: String::from("reset type no longer applies"),
        }
    }

    fn sample_artifact_manifest() -> ArtifactManifest {
        ArtifactManifest {
            artifact_id: String::from("artifact-1"),
            name: String::from("encrypted-backup"),
            total_bytes: 4096,
            sha256: [0xAA; 32].to_vec(),
        }
    }

    fn sample_artifact_chunk() -> ArtifactChunk {
        ArtifactChunk {
            artifact_id: String::from("artifact-1"),
            index: 3,
            data: vec![0x01, 0x02, 0x03],
        }
    }

    #[test]
    fn every_message_round_trips_through_the_wire_format() {
        assert_round_trip(&sample_hello());
        assert_round_trip(&NegotiationResult {
            accepted: true,
            reason: String::new(),
        });
        assert_round_trip(&NegotiationResult {
            accepted: false,
            reason: String::from("baseline-mismatch"),
        });
        assert_round_trip(&sample_capability_manifest());
        assert_round_trip(&CapabilityManifest {
            capabilities: Vec::new(),
            observed_at_unix: 0,
        });
        assert_round_trip(&sample_endpoint_snapshot());
        assert_round_trip(&EndpointSnapshot {
            resources: Vec::new(),
            ..sample_endpoint_snapshot()
        });
        assert_round_trip(&sample_resource_delta());
        assert_round_trip(&sample_event_batch());
        assert_round_trip(&EventBatch { events: Vec::new() });
        assert_round_trip(&sample_operation_offer());
        assert_round_trip(&OperationAccepted {
            operation_id: String::from("operation-1"),
            accepted_at_unix: 1_700_000_110,
        });
        assert_round_trip(&sample_operation_rejected());
        assert_round_trip(&OperationProgress {
            operation_id: String::from("operation-1"),
            state: String::from("running"),
            detail: String::from("waiting for the BMC task"),
        });
        assert_round_trip(&OperationCompleted {
            operation_id: String::from("operation-1"),
            succeeded: true,
            summary: String::from("reset verified"),
        });
        assert_round_trip(&sample_artifact_manifest());
        assert_round_trip(&sample_artifact_chunk());
        assert_round_trip(&Ack { sequence: 12 });
        assert_round_trip(&Heartbeat {
            sent_at_unix: 1_700_000_000,
        });
    }

    #[test]
    fn envelope_round_trips_every_message_variant_and_the_empty_oneof() {
        let messages: Vec<EnvelopeMessage> = vec![
            EnvelopeMessage::Hello(sample_hello()),
            EnvelopeMessage::NegotiationResult(NegotiationResult {
                accepted: true,
                reason: String::new(),
            }),
            EnvelopeMessage::CapabilityManifest(sample_capability_manifest()),
            EnvelopeMessage::EndpointSnapshot(sample_endpoint_snapshot()),
            EnvelopeMessage::ResourceDelta(sample_resource_delta()),
            EnvelopeMessage::EventBatch(sample_event_batch()),
            EnvelopeMessage::OperationOffer(sample_operation_offer()),
            EnvelopeMessage::OperationAccepted(OperationAccepted {
                operation_id: String::from("operation-1"),
                accepted_at_unix: 1_700_000_110,
            }),
            EnvelopeMessage::OperationRejected(sample_operation_rejected()),
            EnvelopeMessage::OperationProgress(OperationProgress {
                operation_id: String::from("operation-1"),
                state: String::from("running"),
                detail: String::new(),
            }),
            EnvelopeMessage::OperationCompleted(OperationCompleted {
                operation_id: String::from("operation-1"),
                succeeded: false,
                summary: String::from("verification mismatch"),
            }),
            EnvelopeMessage::ArtifactManifest(sample_artifact_manifest()),
            EnvelopeMessage::ArtifactChunk(sample_artifact_chunk()),
            EnvelopeMessage::Ack(Ack { sequence: 12 }),
            EnvelopeMessage::Heartbeat(Heartbeat {
                sent_at_unix: 1_700_000_000,
            }),
        ];
        for (sequence, message) in (1_u64..).zip(messages) {
            let envelope = Envelope {
                sequence,
                acked_sequence: sequence - 1,
                message: Some(message),
            };
            assert_round_trip(&envelope);
        }
        assert_round_trip(&Envelope {
            sequence: 1,
            acked_sequence: 0,
            message: None,
        });
    }

    #[test]
    #[allow(clippy::duration_suboptimal_units)]
    fn protocol_constants_are_pinned() {
        assert_eq!(CENTER_PROTOCOL_VERSION, 1);
        assert_eq!(MAX_FRAME_BYTES, 8 * 1024 * 1024);
        assert_eq!(SITE_HEARTBEAT_INTERVAL, Duration::from_secs(30));
        assert_eq!(CENTER_DISCONNECT_AFTER, Duration::from_secs(90));
        assert_eq!(SITE_RECONNECT_AFTER, Duration::from_secs(120));
        assert_eq!(NV_REDFISH_BASELINE, "0.13.0");
    }

    #[test]
    fn enum_wire_names_and_numbers_are_stable() {
        assert_eq!(
            CapabilityState::Unknown.as_str_name(),
            "CAPABILITY_STATE_UNKNOWN"
        );
        assert_eq!(CapabilityState::Unknown as i32, 0);
        assert_eq!(CapabilityState::Compiled as i32, 1);
        assert_eq!(CapabilityState::Advertised as i32, 2);
        assert_eq!(CapabilityState::Usable as i32, 3);

        assert_eq!(ResourceDeltaOp::Unspecified as i32, 0);
        assert_eq!(ResourceDeltaOp::Upsert as i32, 1);
        assert_eq!(ResourceDeltaOp::Delete as i32, 2);

        assert_eq!(TlsTrust::Unspecified as i32, 0);
        assert_eq!(TlsTrust::SystemCa as i32, 1);
        assert_eq!(TlsTrust::PinnedCertificate as i32, 2);

        assert_eq!(EventSeverity::Unspecified as i32, 0);
        assert_eq!(EventSeverity::Ok as i32, 1);
        assert_eq!(EventSeverity::Warning as i32, 2);
        assert_eq!(EventSeverity::Critical as i32, 3);

        assert_eq!(OperationRejectedReason::Unspecified as i32, 0);
        assert_eq!(OperationRejectedReason::EndpointMissing as i32, 1);
        assert_eq!(OperationRejectedReason::CapabilityMissing as i32, 2);
        assert_eq!(OperationRejectedReason::CredentialInvalid as i32, 3);
        assert_eq!(OperationRejectedReason::TargetStateChanged as i32, 4);
        assert_eq!(OperationRejectedReason::Expired as i32, 5);
        assert_eq!(OperationRejectedReason::NotAuthorized as i32, 6);
        assert_eq!(OperationRejectedReason::InvalidCommand as i32, 7);
    }

    #[test]
    fn negotiation_accepts_a_hello_built_for_this_build() {
        assert_eq!(
            negotiate(&sample_hello()),
            crate::NegotiationDecision::Compatible
        );
    }

    #[test]
    fn a_payload_json_must_not_break_the_wire_on_invalid_utf8() {
        // `payload_json` is bytes, not string, so a payload that is not
        // valid UTF-8 still round-trips without a decode error.
        let delta = ResourceDelta {
            payload_json: vec![0xFF, 0xFE, 0x80],
            ..sample_resource_delta()
        };
        assert_round_trip(&delta);
    }
}
