[package]
name = "rutilus-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }
rutilus-domain.workspace = true
secrecy.workspace = true
serde.workspace = true
time = { workspace = true, features = ["serde", "serde-well-known"] }
uuid = { workspace = true, features = ["serde", "rng-getrandom"] }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
